method gImage_2in7b_Black_V2
return dataaddress(array_gImage_2in7b_Black_V2)

method gImage_2in7b_Red_V2
return dataaddress(array_gImage_2in7b_Red_V2)

rem 
rem 	This file was copied from Waveshare C library and modified by Katsumi. 
rem 
rem /*****************************************************************************
rem * | File      	:   ImageData.c
rem * | Author      :   Waveshare team
rem * | Function    :	
rem *----------------
rem * |	This version:   V1.1
rem * | Date        :   2019-06-12
rem * | Info        :
rem *
rem #
rem # Permission is hereby granted, free of charge, to any person obtaining a copy
rem # of this software and associated documnetation files (the "Software"), to deal
rem # in the Software without restriction, including without limitation the rights
rem # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
rem # copies of the Software, and to permit persons to  whom the Software is
rem # furished to do so, subject to the following conditions:
rem #
rem # The above copyright notice and this permission notice shall be included in
rem # all copies or substantial portions of the Software.
rem #
rem # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
rem # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
rem # FITNESS OR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
rem # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
rem # LIABILITY WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
rem # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
rem # THE SOFTWARE.
rem #
rem 
rem ******************************************************************************/

label array_gImage_2in7b_Red_V2
exec $0000,$3f00,$ffff,$ffff,$fffb,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$fffb
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$fffb,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$fff1,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $fff1,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffe3,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffe3,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$fff7,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $fcff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$ffff,$f8ff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$ffff,$f0ff,$ff7f
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$e0ff,$ff7f,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffff,$e0ff,$1f7e,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$e0ff
exec $ff7f,$ffff,$ffff,$ffff,$ffff,$0f00,$3f80,$ffff
exec $ffff,$ffff,$e0ff,$ff7f,$ffff,$ffff,$ffff,$ffff
exec $1000,$3f00,$ffff,$ffff,$ffff,$e0ff,$ff7f,$ffff
exec $ffff,$ffff,$ffff,$1000,$3f00,$ffff,$ffff,$ffff
exec $e0ff,$ff7f,$ffff,$ffff,$ffff,$ffff,$0f00,$3f80
exec $ffff,$ffff,$ffff,$e0ff,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$1000,$3f00,$ffff,$ffff,$ffff,$e0ff,$3f7e
exec $ffff,$ffff,$ffff,$ffff,$1000,$3f00,$ffff,$ffff
exec $ffff,$e0ff,$0f78,$ffff,$ffff,$ffff,$ffff,$0800
exec $3f00,$ffff,$ffff,$ffff,$f0ff,$0ff8,$ffff,$ffff
exec $ffff,$ffff,$1f00,$3f80,$ffff,$ffff,$7ffc,$f0ff
exec $0ff0,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$1ff8,$f1ff,$1fe0,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$03fe,$fbff,$3fe0,$ffff
exec $ffff,$ffff,$ffff,$0f00,$3f00,$ffff,$ffff,$87ff
exec $ffff,$7fe0,$ffff,$ffff,$ffff,$ffff,$1000,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffe0,$ffff,$ffff,$ffff
exec $ffff,$1000,$3f80,$ffff,$ffff,$ffff,$ffff,$fcff
exec $ffff,$ffff,$ffff,$ffff,$1000,$3f80,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$ffff,$ffff,$ffff,$ffff,$0f00
exec $3f00,$ffff,$ffff,$c7ff,$ffff,$e0ff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$8fff,$ffff
exec $c1ff,$ffff,$ffff,$ffff,$ffff,$1000,$3f80,$ffff
exec $ffff,$1fff,$ffff,$07ff,$ffff,$ffff,$ffff,$ffff
exec $1000,$3f80,$ffff,$ffff,$3fff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1000,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0f00,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0c00,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1400,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1400,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1400,$3f80,$ffff,$ffff,$ffff,$ffff,$fff8
exec $ffff,$ffff,$ffff,$ffff,$0f00,$3f00,$ffff,$ffff
exec $ffff,$ffff,$7f78,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$7e00,$ffff,$ffff
exec $ffff,$ffff,$1000,$3f00,$ffff,$ffff,$ffff,$feff
exec $7800,$ff7f,$ffff,$ffff,$ffff,$1000,$3f00,$ffff
exec $ffff,$ffff,$feff,$3833,$ff7f,$ffff,$ffff,$ffff
exec $1f00,$3f80,$ffff,$ffff,$ffff,$ffff,$3833,$ff7f
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$0330,$ff7f,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$0780,$ff0f,$ffff,$ffff
exec $ffff,$0f00,$3f80,$ffff,$ffff,$ffff,$ffff,$c380
exec $ff07,$ffff,$ffff,$ffff,$1400,$3f80,$ffff,$ffff
exec $ffff,$e1ff,$d8f7,$ff0f,$ffff,$ffff,$ffff,$1400
exec $3f80,$ffff,$ffff,$ffff,$c0ff,$f03f,$ffcf,$ffff
exec $ffff,$ffff,$1400,$3f80,$ffff,$ffff,$ffff,$c2ff
exec $fe0f,$ffdf,$ffff,$ffff,$ffff,$1300,$3f00,$ffff
exec $ffff,$ffff,$e7ff,$fc7f,$ff7f,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$e6ff,$f47f,$ff7f
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $e0ff,$f93f,$ff7f,$ffff,$ffff,$ffff,$0f00,$3f80
exec $ffff,$ffff,$ffff,$c2ff,$fe7f,$ffff,$ffff,$ffff
exec $ffff,$1000,$3f00,$ffff,$ffff,$ffff,$c7ff,$f63d
exec $ffff,$ffff,$ffff,$ffff,$1000,$3f00,$ffff,$ffff
exec $ffff,$e7ff,$c030,$ff4f,$ffff,$ffff,$ffff,$0800
exec $3f00,$ffff,$ffff,$ffff,$f0ff,$01c0,$ff87,$ffff
exec $ffff,$ffff,$7f00,$3f80,$ffff,$ffff,$ffff,$feff
exec $01c0,$ff8f,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$ffff,$feff,$0940,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$feff,$9c0d,$ff7f
exec $ffff,$ffff,$ffff,$1300,$3f00,$ffff,$ffff,$ffff
exec $feff,$8c0d,$ff7f,$ffff,$ffff,$ffff,$1200,$3f80
exec $ffff,$ffff,$ffff,$feff,$f001,$ff7f,$ffff,$ffff
exec $ffff,$1400,$3f80,$ffff,$ffff,$ffff,$ffff,$7c00
exec $ffff,$ffff,$ffff,$ffff,$0c00,$3f80,$ffff,$ffff
exec $ffff,$ffff,$7f78,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$fff8,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $fff9,$ffff,$ffff,$ffff,$ffff,$0c00,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $1400,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1400,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1400,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0f00,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1800
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0100,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$ffff,$dfff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$03ff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0f00,$3f80,$ffff,$ffff,$01fe,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1400,$3f80,$ffff,$ffff
exec $00fe,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1400
exec $3f80,$ffff,$feff,$007e,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$1400,$3f80,$ffff,$fcff,$001c,$ff7f
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1300,$3f00,$ffff
exec $f8ff,$000c,$ff3f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$f0ff,$0004,$e03f,$ff7f,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$f0ff,$0000
exec $803f,$ff3f,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$f0ff,$0000,$003e,$ff1f,$ffff,$ffff,$ffff
exec $ffff,$0100,$3f80,$ffff,$e0ff,$2000,$003c,$ff0f
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$e0ff
exec $0c00,$0014,$ff1f,$ffff,$ffff,$ffff,$ffff,$1800
exec $3f00,$ffff,$e0ff,$1e0c,$002f,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$e0ff,$1e1e,$000f
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$0100,$3f80,$ffff
exec $f0ff,$1e1e,$000f,$ff3f,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$f0ff,$201e,$0006,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$f0ff,$0004
exec $0c00,$ff78,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$f0ff,$0000,$1e00,$7f80,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f80,$ffff,$f8ff,$0000,$3e00,$3f00
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$07fc
exec $0000,$1c00,$3f00,$ffff,$ffff,$ffff,$ffff,$1800
exec $3f00,$ffff,$07f0,$0080,$0800,$3f00,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$07c0,$6080,$40c0
exec $3f00,$ffff,$ffff,$ffff,$ffff,$0100,$3f80,$ffff
exec $0780,$7960,$c0c1,$3f00,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$0080,$3f7f,$00ef,$7f00,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$0000,$ff1f
exec $40fe,$7fe0,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$0000,$ff03,$01fc,$ffe0,$ffff,$ffff,$ffff
exec $ffff,$0100,$3f80,$feff,$0000,$ff09,$f9ff,$ffe1
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$3800
exec $ff0f,$f8ff,$ffe3,$ffff,$ffff,$ffff,$ffff,$1800
exec $3f00,$ffff,$7880,$ff01,$80ff,$ff07,$ffff,$ffff
exec $ffff,$ffff,$1800,$3f00,$ffff,$7cc0,$ff3f,$70ff
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff
exec $39e0,$ffff,$f0ff,$ff3f,$ffff,$ffff,$ffff,$ffff
exec $0100,$3f80,$ffff,$00f0,$ff7f,$00fc,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$0600,$3f00,$ffff,$00e0,$ff0f
exec $00fe,$ff3f,$ffff,$ffff,$ffff,$ffff,$1800,$3f00
exec $ffff,$0080,$ff3f,$80ff,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$0600,$3f00,$ffff,$0000,$ff7f,$e0ff,$ff03
exec $ffff,$ffff,$ffff,$ffff,$0100,$3f80,$feff,$3800
exec $ff03,$f8ff,$fff1,$ffff,$ffff,$ffff,$ffff,$0600
exec $3f00,$ffff,$3c00,$e30f,$3cfe,$fff0,$ffff,$ffff
exec $ffff,$ffff,$1800,$3f00,$ffff,$7c00,$031f,$04e7
exec $7ff0,$ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff
exec $3880,$0338,$00c1,$7f60,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$02c0,$0120,$0080,$3f00,$ffff
exec $ffff,$ffff,$ffff,$0100,$3f80,$ffff,$00e0,$0000
exec $0000,$3f00,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$01f0,$00e0,$0700,$3f80,$ffff,$ffff,$ffff
exec $ffff,$1800,$3f00,$ffff,$01fc,$00e0,$0700,$3f80
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$f9ff
exec $00e0,$0700,$7f80,$ffff,$ffff,$ffff,$ffff,$0100
exec $3f80,$ffff,$f8ff,$00c0,$0300,$7f00,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$f8ff,$0000,$8001
exec $ff40,$ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff
exec $f0ff,$c001,$c003,$ff7f,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$f0ff,$e301,$e003,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$e0ff,$e703
exec $c081,$ff3f,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$e0ff,$c701,$8080,$ff1f,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$e0ff,$8700,$0080,$ff1f
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$e0ff
exec $0000,$0024,$ff0f,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$f0ff,$0000,$0026,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$f0ff,$0000,$803f
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $f8ff,$0000,$e03f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$f8ff,$0004,$ff3f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$fcff,$001e
exec $ff7f,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$feff,$003e,$ff7f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$00fe,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1000,$3f80,$ffff,$ffff
exec $01fe,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1000
exec $3f80,$ffff,$ffff,$07ff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3f00,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1000,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0c00,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1400,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1400,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1400,$3f80,$ffff,$ffcf
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0f00
exec $3f00,$ffff,$fc87,$ff3f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$f883,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $f081,$ff3c,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0f00,$3f80,$ffff,$f8c0,$7f3c,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1000,$3f00,$ffff,$78e0,$ff3c
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1000,$3f00
exec $ffff,$38e0,$ff7c,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0800,$3f00,$ffff,$38f0,$ff79,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1f00,$3f80,$ffff,$3cf8
exec $fffb,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$3ffe,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$3fff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e3ff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $c0ff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$c0ff,$ff7f,$ffff,$0c00,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$80e3,$ff7f
exec $ffff,$1400,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$80c1,$ff3f,$ffff,$1400,$3f80,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$8080,$c33f,$ffff,$1400
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0080
exec $013f,$ffff,$0f00,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$003e,$ffff,$0000,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0700,$003c,$ffff
exec $1000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $8701,$010e,$ffff,$1000,$3f00,$e3ff,$ffff,$7ffe
exec $ffff,$ffff,$ffff,$c703,$010e,$ffff,$1f00,$3f80
exec $c7ff,$ffff,$7ffc,$ff7f,$ffff,$ffff,$c201,$010e
exec $ffff,$0000,$3f00,$87ff,$ffff,$7ff8,$ffff,$ffff
exec $ffff,$8001,$3100,$ffff,$0000,$3f00,$9fff,$ffff
exec $e7f1,$ffff,$ffff,$ffff,$0080,$7800,$ff07,$0f00
exec $3f80,$feff,$ff7f,$e3e1,$ffff,$ffff,$feff,$00b0
exec $7800,$ff07,$1400,$3f80,$feff,$ff7f,$e3e3,$ffff
exec $ffff,$f0ff,$0078,$3000,$ff07,$1400,$3f80,$feff
exec $ffff,$f3ef,$ffff,$ffff,$c0ff,$1878,$80c0,$ff07
exec $1400,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$80ff
exec $0c37,$80e3,$ff07,$1300,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ef07,$03ee,$ff0f,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fe,$ff01,$07fc
exec $ff0f,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $00fe,$7f00,$f7ff,$ff1f,$0f00,$3f80,$ffff,$ffff
exec $ffff,$ffff,$ffff,$01ff,$ffc0,$e3ff,$ff3f,$1000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$81ff,$7fc0
exec $00ff,$ffff,$1000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$c1ff,$ffcf,$c1ff,$ffff,$0800,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$c0ff,$ff8f,$c1fd,$ffff
exec $7f00,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$c0ff
exec $ff01,$01fe,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$80ff,$ff7f,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fe,$7f86,$e3ff
exec $ff1f,$1300,$3f00,$ffff,$ffff,$feff,$ff1f,$ffff
exec $01fe,$f9c0,$f7fe,$ff8f,$1200,$3f80,$ffff,$ffff
exec $f8ff,$ff07,$ffff,$01ff,$e1c3,$17e6,$ff8f,$1400
exec $3f80,$ffff,$ffff,$f0ff,$ff07,$ffff,$81ff,$00c7
exec $03c0,$ff07,$0c00,$3f80,$ffff,$ffff,$c0ff,$ff07
exec $ffff,$c0ff,$0020,$0080,$ff07,$0000,$3f00,$ffff
exec $ffff,$f0ff,$ff0f,$ffff,$e0ff,$000c,$1c00,$ff07
exec $0000,$3f00,$ffff,$ffff,$feff,$ff3f,$ffff,$ffff
exec $00de,$1e00,$ff07,$0c00,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$00ce,$1c00,$ff07,$1400,$3f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00c0,$0001
exec $ff0f,$1400,$3f80,$ffff,$ffff,$ffff,$ffe3,$ffff
exec $ffff,$30c0,$8103,$ffff,$1400,$3f80,$ffff,$ffff
exec $ffff,$ffc7,$ffff,$ffff,$7980,$8183,$ffff,$0f00
exec $3f00,$ffff,$ffff,$ffff,$ff87,$ffff,$ffff,$7b80
exec $81c3,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ff0f
exec $ffff,$ffff,$3100,$00d0,$ffff,$1800,$3f00,$ffff
exec $ffff,$feff,$ff0f,$ffff,$ffff,$0080,$009c,$ffff
exec $0600,$3f00,$ffff,$ffff,$feff,$ff3f,$ffff,$ffff
exec $0080,$001e,$ffff,$0100,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0080,$833f,$ffff,$0600,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$80c0,$ff3f
exec $ffff,$1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$c0e3,$ff3f,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$c0f7,$ff7f,$ffff,$0f00
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$c0ff
exec $ffff,$ffff,$1400,$3f80,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$e3ff,$ffff,$ffff,$1400,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $1400,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1300,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0100
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0100,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0100,$3f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0100
exec $3f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0600,$3f00,$ffff,$87ff,$ffff
exec $fff9,$ffff,$ffff,$ffff,$ffff,$ffff,$0100,$3f80
exec $ffff,$81ff,$ffff,$fff1,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0600,$3f00,$ffff,$c0ff,$ffff,$ffe3,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1800,$3f00,$ffff,$e0ff
exec $ff7f,$ffc3,$ffff,$ffff,$ffff,$ffff,$ffff,$0600
exec $3f00,$ffff,$f0ff,$ff7f,$ffc7,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0100,$3f80,$ffff,$fcff,$ffff,$ffdf
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $1800,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0600,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0100,$3f80,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0600,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1800
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0600,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0100,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0600,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1800,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$3f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
label array_gImage_2in7b_Black_V2
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$feff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff,$ff3f
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ff9f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffcf,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffe7,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$fff3,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fff9,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$fff8,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$7ffc,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$3ffe
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$1fff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0fff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $87ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$c3ff,$ffff,$ffff,$ffff,$ffff
exec $fff7,$ffff,$ffff,$ffff,$ffff,$ffff,$e3ff,$ffff
exec $ffff,$ffff,$ffff,$fff7,$ffff,$ffff,$ffff,$ffff
exec $ffff,$e1ff,$ffff,$ffff,$ffff,$ffff,$fff3,$ffff
exec $ffff,$ffff,$ffff,$ffff,$f0ff,$ffff,$ffff,$ffff
exec $ffff,$fff3,$ffff,$ffff,$ffff,$ffff,$ffff,$f8ff
exec $ff7f,$ffff,$ffff,$ffff,$fff3,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fff1
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffe1,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffe1,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffe1,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffe0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffe0,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffe0,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$7fc0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$7fc0
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$7fc0,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3fc0,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $3fc0,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1fc0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1fc0,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0f80
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0f80,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1f80,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $1f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$3f80,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fffb,$3f80,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$dfff
exec $fffd,$7f80,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$cfff,$fffc,$7f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c7ff,$7ffc,$ff00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $c3ff,$1ffe,$ff00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$e1ff,$0ffe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$e0ff,$07fe
exec $ff01,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$e0ff,$007f,$ff01,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$f0ff,$003f,$ff03,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f0ff
exec $001f,$ff03,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$000f,$ff07,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f8ff,$000f,$ff07
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$9fff,$ffff
exec $f8ff,$0000,$ff07,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$c7ff,$ff3f,$fcff,$0000,$ff0f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$c0ff,$ff3f,$fcff,$0000
exec $ff0f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$e0ff
exec $ff3f,$fcff,$0000,$ff0f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$e0ff,$ff1f,$feff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$ff1f,$feff
exec $0000,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $f8ff,$ff1f,$feff,$0000,$ff1f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$f8ff,$ff1f,$ffff,$0000,$ff1f
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$ff0f
exec $ffff,$0000,$ff1f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$fcff,$ff0f,$ffff,$0000,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$feff,$ff0f,$ffff,$0000
exec $ff1f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ff07,$e0ff,$0000,$ff1f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ff07,$e0ff,$0000,$ff1f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ff83,$f0ff
exec $0000,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ff83,$f0ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffc3,$f8ff,$0000,$ff0f
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffc1
exec $f8ff,$0000,$ff07,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffe1,$fcff,$0000,$ff07,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fff0,$ffff,$0000
exec $ff03,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $fff0,$ffff,$0080,$ff03,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$7ff8,$ffff,$0080,$ff01,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$7ff8,$ffff
exec $0080,$ff01,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$3ffc,$feff,$0000,$ff00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1ffc,$f8ff,$0000,$7f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0ffe
exec $f8ff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0ffe,$f0ff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$07ff,$f0ff,$0000
exec $1f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $03ff,$f0ff,$0000,$0f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$01ff,$f0ff,$0000,$0f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00ff,$e0ff
exec $0000,$0700,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$00df,$c03f,$0000,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00cf,$001f,$0000,$ff01
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00c0
exec $0000,$0000,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$0000,$ff3f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$fcff,$0000,$0000,$0000
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff
exec $0000,$0000,$0100,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$0000,$0000,$0300,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0080,$0000
exec $0700,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$00e0,$0000,$0700,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00f8,$0000,$0f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00ff
exec $0000,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$1f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e0ff,$0000,$3f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $f0ff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$f0ff,$0000,$3f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$0000
exec $3f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f0ff,$0000,$3f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00ff,$0000,$1f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f7ff,$00fc
exec $0000,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f0ff,$0000,$0000,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$f0ff,$0000,$0000,$0700
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f0ff
exec $0000,$0000,$0300,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$0000,$0000,$0100,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$0000,$0000
exec $0000,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0000,$0000,$0000,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00c0,$0000,$0300,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00e0
exec $0000,$0700,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00e0,$0000,$ff00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00e0,$0000,$ff00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $00e0,$0000,$ff00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$00e0,$0000,$ff00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00e0,$0000
exec $ff00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$00c0,$0000,$ff00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00c0,$0000,$ff00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0080
exec $0000,$ff00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$ff01,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$0000,$ff01
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff
exec $0000,$0000,$ff01,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$fcff,$0000,$0000,$ff03,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f8ff,$0000,$3c00
exec $ff07,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $e0ff,$0000,$ff00,$ff8f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$00ff,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00ff,$0000
exec $ff07,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$80ff,$0000,$ff0f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$fcff,$0000,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fcff
exec $0000,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$fcff,$0100,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$0300,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $f0ff,$0700,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$e0ff,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$0f00
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$0f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$fcff,$0f00,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff
exec $0f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$feff,$0f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0f00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$0f00,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$0700
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0780,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0780,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$0000,$ff3f
exec $0780,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0080,$0000,$3f00,$0780,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fe,$0700,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $fcff,$0300,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$03c0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$03c0
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03c0,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0180,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $0100,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$7f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$feff,$ff00,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $feff,$ff01,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$feff,$ff03,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$ff07
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$fcff,$ff07,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$fcff,$ff0f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f8ff
exec $ff1f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f8ff,$ff3f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f8ff,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $f0ff,$ff7f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$f0ff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$e0ff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$e1ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$c1ff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$83ff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07e0,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$e0ff,$0700,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$e0ff
exec $0f0e,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$71ff,$0ffe,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$1ffe,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$1ffe,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$3ffc,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$7ff8
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$7ff8,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fff0,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffe0,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffc1,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffc3,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ff83,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ff07,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff,$ff0f
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$feff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$fcff,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f8ff
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$ff7f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $e0ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$c0ff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$80ff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$80ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$00ff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$00fe
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$01fe,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$01fc,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $39f8,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$79f0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$fbf0,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$fbe1,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffc3,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffc7
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ff8f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$feff
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$feff,$ff7f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $f9ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$f1ff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$f3ff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$e7ff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$cfff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$9fff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$bfff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7fff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $fffe,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$fffd,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$fffb,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffe7,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffef
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffdf,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
