method gImage_2in13b_r
return dataaddress(array_gImage_2in13b_r)

method gImage_2in13b_b
return dataaddress(array_gImage_2in13b_b)

rem 
rem 	This file was copied from Waveshare C library and modified by Katsumi. 
rem 
rem /*****************************************************************************
rem * | File      	:   ImageData.c
rem * | Author      :   Waveshare team
rem * | Function    :	
rem *----------------
rem * |	This version:   V1.1
rem * | Date        :   2019-06-12
rem * | Info        :
rem *
rem #
rem # Permission is hereby granted, free of charge, to any person obtaining a copy
rem # of this software and associated documnetation files (the "Software"), to deal
rem # in the Software without restriction, including without limitation the rights
rem # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
rem # copies of the Software, and to permit persons to  whom the Software is
rem # furished to do so, subject to the following conditions:
rem #
rem # The above copyright notice and this permission notice shall be included in
rem # all copies or substantial portions of the Software.
rem #
rem # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
rem # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
rem # FITNESS OR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
rem # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
rem # LIABILITY WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
rem # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
rem # THE SOFTWARE.
rem #
rem 
rem ******************************************************************************/

label array_gImage_2in13b_b
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $bfff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffcf
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e0ff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$3ff8,$ffff,$ffff,$ffff
exec $ffff,$ffff,$feff,$ff0f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$07ff,$ffff,$ffff,$ffff,$ffff,$e7ff,$ffff
exec $ffc3,$ffff,$ffff,$ffff,$ffff,$ffc7,$c0ff,$ff3f
exec $ffff,$ffff,$ffff,$e7ff,$ffff,$0fe0,$ffff,$ffff
exec $ffff,$ffff,$ffe7,$f0ff,$ff07,$ffff,$ffff,$ffff
exec $e7ff,$ffff,$07f8,$ffff,$ffff,$ffff,$ffff,$ffe7
exec $fcff,$ff03,$ffff,$ffff,$ffff,$e7ff,$ffff,$01fe
exec $ffff,$ffff,$ffff,$ffff,$ffe7,$ffff,$ff00,$ffff
exec $ffff,$ffff,$e7ff,$ffff,$80ff,$ffff,$ffff,$ffff
exec $ffff,$ffe7,$ffff,$ffc0,$ffff,$ffff,$ffff,$e7ff
exec $ffff,$c0ff,$ffff,$ffff,$ffff,$ffff,$ffe7,$ffff
exec $7fe0,$ffff,$ffff,$ffff,$e7ff,$ffff,$e0ff,$ff7f
exec $ffff,$ffff,$ffff,$ffe7,$ffff,$7fe0,$ffff,$ffff
exec $ffff,$e7ff,$ffff,$f0ff,$ff7f,$ffff,$ffff,$ffff
exec $ffe7,$ffff,$7ff0,$ffff,$ffff,$ffff,$e7ff,$ffff
exec $f0ff,$df7f,$ffff,$ffff,$ffff,$ffe7,$ffff,$7ff0
exec $ffbf,$ffff,$ffff,$e7ff,$ffff,$f0ff,$7f7e,$ffff
exec $ffff,$ffff,$ffe7,$ffff,$7ef0,$ff7f,$ffff,$ffff
exec $e7ff,$ffff,$f0ff,$ff7c,$ffff,$ffff,$ffff,$ffe7
exec $ffff,$7df0,$ffff,$ffff,$ffff,$e7ff,$fcff,$e003
exec $fffd,$ffff,$ffff,$ffff,$ffe7,$00f8,$79e0,$ffff
exec $ffff,$ffff,$e7ff,$f0ff,$6000,$ffff,$ffff,$ffff
exec $ffff,$ffe7,$00e0,$f830,$1f00,$ffff,$ffff,$e7ff
exec $c0ff,$1160,$0080,$ff1f,$ffff,$ffff,$ffe7,$3000
exec $0019,$1f00,$ffff,$ffff,$e7ff,$40fe,$0820,$0000
exec $ffff,$ffff,$ffff,$c1e7,$00c0,$0008,$ff7f,$ffff
exec $ffff,$e7ff,$c080,$0820,$ff00,$ffff,$ffff,$ffff
exec $00e7,$204c,$0708,$ffff,$ffff,$ffff,$e6ff,$0410
exec $0020,$ff1d,$ffff,$ffff,$ffff,$10e6,$2004,$7c40
exec $f9ff,$ffff,$ffff,$e4ff,$0010,$8000,$fffc,$7fe0
exec $ffff,$ffff,$0ce4,$0300,$fc0f,$e47f,$ff3f,$ffff
exec $e4ff,$000e,$1fc0,$7ffc,$1fc0,$ffff,$ffff,$0be4
exec $e083,$fc0f,$c27f,$ff1f,$ffff,$e6ff,$0700,$0ff0
exec $7ffe,$0fc1,$ffff,$ffff,$00e6,$f007,$fe07,$c07f
exec $ff8f,$ffff,$e7ff,$0700,$03f0,$7ffe,$7fe0,$ffff
exec $ffff,$80e7,$f303,$fe01,$e07f,$ff1f,$ffff,$e7ff
exec $03c0,$80e3,$7ffe,$1ff0,$ffff,$ffff,$f8e7,$c000
exec $fce0,$f07f,$ff87,$ffff,$e7ff,$00f7,$3c00,$7ffc
exec $83f0,$ffff,$ffff,$f9e7,$0080,$fc18,$f0ff,$ff81
exec $ffff,$e7ff,$809d,$0004,$fffc,$c1f1,$ffff,$ffff
exec $35e6,$0401,$fd00,$f3ff,$ff71,$ffff,$e6ff,$0262
exec $0000,$fffd,$01e2,$ffff,$ffff,$c2e4,$0002,$fb00
exec $e2ff,$ff01,$ffff,$e5ff,$0282,$0100,$fff3,$01e0
exec $ffff,$ffff,$01e3,$000e,$f303,$e4ff,$ff01,$ffff
exec $e6ff,$8301,$7f00,$ffe7,$00c0,$ffff,$ffff,$01e4
exec $0081,$cfff,$e0ff,$3f00,$ffff,$e0ff,$8001,$ff00
exec $ff8f,$00e0,$ff1f,$ffff,$03e0,$01c0,$9fff,$e0ff
exec $1f01,$ffff,$e0ff,$f80f,$ff01,$ffdf,$16fc,$ff1f
exec $ffff,$1fe0,$c7f0,$3ff8,$f6ff,$1f1f,$ffff,$e0ff
exec $c03f,$f06f,$ff1f,$01e2,$ff1f,$ffff,$7fe0,$3fc0
exec $0fc0,$ccff,$9f00,$ffff,$e0ff,$c0ff,$c01f,$ff0f
exec $00de,$ff19,$ffff,$ffe0,$0f80,$0f80,$9fff,$0000
exec $ffff,$e1ff,$80ff,$0040,$ff07,$fe9f,$ff00,$ffff
exec $fff3,$c080,$0700,$bfff,$00ff,$ff7f,$e7ff,$c0ff
exec $0080,$ff07,$ffbf,$7f90,$ffff,$ffe7,$80c7,$0f00
exec $bfff,$d8ff,$ff7f,$e7ff,$e0ff,$00c0,$ff3f,$ff3f
exec $7fe0,$ffff,$ffe7,$c0e0,$1f00,$3fff,$f0ff,$ffff
exec $e7ff,$f0ff,$8020,$ff07,$ff3f,$ffff,$ffff,$ffe7
exec $30e0,$0300,$7fff,$ffff,$ffff,$e7ff,$c0ff,$4030
exec $ff03,$ff3f,$ffff,$ffff,$fce7,$1040,$0360,$7fff
exec $ffff,$ffff,$e7ff,$c0e0,$3c18,$fe07,$ff7f,$ffff
exec $ffff,$87e7,$08c0,$0f18,$7ffc,$ffff,$ffff,$f7ff
exec $e00f,$1008,$fc1f,$ffff,$ffff,$ffff,$7ff6,$0cfe
exec $4310,$fff9,$ffff,$ffff,$f0ff,$f1ff,$1004,$f381
exec $ffff,$ffff,$ffff,$fff1,$04e1,$8111,$ffe3,$ffff
exec $ffff,$f3ff,$c0ff,$1106,$4f80,$ffff,$ffff,$ffff
exec $fff3,$02c0,$0010,$ff7f,$ffff,$ffff,$f7ff,$c0ff
exec $1022,$7f08,$ffff,$ffff,$ffff,$fff7,$3ac0,$0c30
exec $ff7f,$ffff,$ffff,$f7ff,$c2ff,$0018,$7f0c,$ffff
exec $ffff,$ffff,$fff7,$10c3,$1c00,$ff7f,$ffff,$ffff
exec $f7ff,$c1ff,$0080,$7f60,$ffff,$ffff,$ffff,$fff7
exec $c080,$c000,$ff3f,$ffff,$ffff,$f7ff,$80ff,$01c0
exec $3f80,$ffff,$ffff,$ffff,$f0f7,$3000,$0000,$ff1f
exec $ffff,$ffff,$f7ff,$e003,$e000,$1f00,$ffff,$ffff
exec $ffff,$0ff6,$01f0,$02f0,$ff3f,$ffff,$ffff,$f0ff
exec $f8ff,$f803,$3f3c,$ffff,$ffff,$ffff,$e0f1,$0704
exec $00f8,$ff7f,$ffff,$ffff,$f3ff,$0280,$f807,$ff00
exec $ffff,$ffff,$ffff,$0ff6,$07fe,$01f8,$ffff,$ffff
exec $ffff,$f0ff,$fc7f,$f803,$bf03,$ffff,$ffff,$ffff
exec $e0f1,$2110,$03f0,$ff27,$ffff,$ffff,$f3ff,$c007
exec $60c0,$9181,$ffff,$ffff,$ffff,$3ff0,$00c1,$c100
exec $ffd8,$ffff,$ffff,$f0ff,$877f,$0004,$4c60,$ff3f
exec $ffff,$ffff,$fff3,$0c86,$2000,$3f4f,$ffff,$ffff
exec $f7ff,$80ff,$0818,$0f10,$ffff,$ffff,$ffff,$fff7
exec $18c0,$0808,$ff0f,$ffff,$ffff,$f7ff,$c0ff,$4c10
exec $1f0f,$ffff,$ffff,$ffff,$00f7,$0040,$0c44,$ff3f
exec $ffff,$ffff,$f0ff,$0000,$460c,$3f0c,$ffff,$ffff
exec $ffff,$00f0,$1c30,$0cc6,$ff3f,$ffff,$ffff,$f1ff
exec $f8ff,$c6f8,$3f0c,$ffff,$ffff,$ffff,$00f0,$001c
exec $0cc6,$ff3f,$ffff,$ffff,$f0ff,$0c00,$c300,$3f00
exec $ffff,$ffff,$ffff,$80f3,$0018,$00c3,$ff3f,$ffff
exec $ffff,$f7ff,$70ff,$c100,$3f00,$ffff,$ffff,$ffff
exec $fff7,$00e0,$80c3,$ff7f,$ffff,$ffff,$f3ff,$c0ff
exec $c700,$ff0f,$ffff,$ffff,$ffff,$fff1,$0080,$07c6
exec $ff9f,$ffff,$ffff,$f0ff,$c07f,$c408,$0f03,$ffff
exec $ffff,$ffff,$0ff0,$18c0,$03c0,$ff47,$ffff,$ffff
exec $f3ff,$8083,$c020,$3902,$ffff,$ffff,$ffff,$e0f0
exec $00c0,$02c0,$7f0c,$ffff,$ffff,$f0ff,$401c,$7043
exec $03fc,$ff3f,$ffff,$ffff,$0ff0,$c220,$ec31,$8f03
exec $ffff,$ffff,$f0ff,$9f03,$03c4,$00ff,$ffc7,$ffff
exec $ffff,$00f0,$e06f,$3f07,$6380,$ffff,$ffff,$f7ff
exec $3100,$04e0,$c0ff,$ff31,$ffff,$ffff,$e0f7,$f018
exec $ff01,$1cf0,$ffff,$ffff,$f7ff,$0ef8,$0b30,$f0ff
exec $7f0c,$ffff,$ffff,$fcf7,$1807,$ff1f,$0ffc,$ff3f
exec $ffff,$f3ff,$07fe,$3f1c,$feff,$9f07,$ffff,$ffff
exec $fff3,$cf83,$ffff,$03ff,$ff8f,$ffff,$f3ff,$c3ff
exec $ffe7,$ffff,$e783,$ffff,$ffff,$fff3,$f7c1,$ffff
exec $81ff,$ffe3,$ffff,$f3ff,$e1ff,$fff3,$ffff,$f1c1
exec $ffff,$ffff,$fff3,$fbe0,$ffff,$e0ff,$fff9,$ffff
exec $f3ff,$f0ff,$fff9,$ffff,$fcf0,$ffff,$ffff,$fff3
exec $fdf8,$ffff,$f8ff,$fffe,$ffff,$f3ff,$f8ff,$ff7c
exec $ffff,$7ffc,$ff7f,$ffff,$fff3,$7cfc,$ff7f,$feff
exec $3f7f,$ffff,$f3ff,$fcff,$7f3e,$ffff,$7fff,$ffbf
exec $ffff,$fff3,$3efe,$ff3f,$ffff,$dfff,$ffff,$f3ff
exec $feff,$3f3f,$ffff,$ffff,$ffcf,$ffff,$fff3,$3fff
exec $f03f,$ffff,$efff,$ffff,$f3ff,$feff,$bf3f,$03f0
exec $ffff,$ffc7,$ffff,$fff3,$3ffe,$e0bf,$ff01,$e7ff
exec $ffff,$f3ff,$ffff,$9f3f,$00e0,$ffff,$ffe7,$ffff
exec $fff3,$3fff,$f0df,$7f00,$f3ff,$ffff,$f3ff,$ffff
exec $df3f,$00fb,$ff7f,$fff3,$ffff,$fff3,$3fff,$f0df
exec $7f00,$fbff,$ffff,$f3ff,$ffff,$df7f,$10c0,$ff3f
exec $fffb,$ffff,$fff3,$ffff,$c0df,$3f10,$fbff,$ffff
exec $f3ff,$ffff,$dfff,$10c0,$ff1f,$fffb,$ffff,$fff3
exec $ffff,$c1df,$1ff8,$fbff,$ffff,$f3ff,$ffff,$dfff
exec $0cc0,$ff0f,$fffb,$ffff,$fff3,$ffff,$e0df,$0306
exec $f3ff,$ffff,$f3ff,$ffff,$dfff,$03e0,$1f00,$fff3
exec $ffff,$fff3,$ffff,$f8df,$c001,$e703,$ffff,$f3ff
exec $ffff,$dfff,$00fc,$017f,$ffe7,$ffff,$fff3,$ffff
exec $fcdf,$3f00,$c7c0,$ffff,$f3ff,$ffff,$dfff,$00fc
exec $0000,$ffef,$ffff,$fff3,$ffff,$fcdf,$0000,$df00
exec $ffff,$f3ff,$ffff,$dfff,$00fc,$0000,$ffdf,$ffff
exec $fff3,$ffff,$fe9f,$0000,$ff00,$ffff,$f3ff,$ffff
exec $1fff,$80ff,$0000,$ffff,$ffff,$fff3,$feff,$ff1f
exec $00e0,$1f00,$ffff,$f3ff,$ffff,$1ffc,$f0ff,$0000
exec $ff1f,$ffff,$fff3,$ffff,$ff9f,$00f0,$1f18,$ffff
exec $f3ff,$ffff,$dfff,$f0ff,$3000,$ff1f,$ffff,$fff3
exec $ffff,$ffdf,$83f1,$3fc0,$ffff,$f3ff,$ffff,$cffe
exec $e0ff,$01ff,$ff3f,$ffff,$fff3,$84ff,$ffcf,$7000
exec $1f01,$ffff,$f3ff,$ffff,$6706,$00fe,$0240,$ff3f
exec $ffff,$fff3,$07fe,$fee7,$4000,$3f06,$ffff,$fbff
exec $fcff,$e103,$00fe,$0640,$ff7f,$ffff,$fffb,$04fc
exec $ff60,$4000,$ff0c,$ffff,$fbff,$feff,$3018,$807f
exec $1800,$ffff,$ffff,$fffb,$38e0,$3f36,$00c0,$ff19
exec $ffff,$fbff,$c0ff,$3320,$f01f,$3100,$ffff,$ffff
exec $fffb,$c8c0,$8f11,$00f8,$ff63,$ffff,$fbff,$80ff
exec $39c0,$fc8f,$6300,$ffff,$ffff,$fffb,$80f9,$c748
exec $00fc,$ff43,$ffff,$fbff,$bfff,$c406,$fc07,$c300
exec $ffff,$ffff,$fefb,$0703,$0786,$0cfc,$ff83,$ffff
exec $fbff,$01fe,$8607,$fc07,$831e,$ffff,$ffff,$fcfb
exec $0705,$0793,$1dfc,$ff81,$ffff,$fbff,$08fc,$b10f
exec $fe03,$e123,$ffff,$ffff,$fffb,$fff8,$2399,$e7ff
exec $ff30,$ffff,$fbff,$00fe,$c0ff,$ff91,$1080,$ff7f
exec $ffff,$fcfb,$ff00,$98e0,$00ff,$7f00,$ffff,$ffff
exec $00fc,$e0ff,$7f8c,$0000,$ff7f,$ffff,$fcff,$ff21
exec $80f8,$007f,$7f00,$ffff,$ffff,$71fc,$fcff,$7f80
exec $0000,$ffff,$ffff,$ffff,$ffff,$40fe,$803f,$ff00
exec $ffff,$ffff,$ffff,$ffff,$3fc0,$0180,$ffff,$ffff
exec $ffff,$ffff,$80ff,$e03f,$ff01,$ffff,$ffff,$ffff
exec $ffff,$7fc0,$01fc,$ffff,$ffff,$ffff,$ffff,$e0ff
exec $fc3f,$ff01,$ffff,$ffff,$ffff,$ffff,$3ff8,$01fc
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fcff,$ff03,$ffff
exec $ffff,$ffff,$ffff,$ffff,$07fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ff9f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff
label array_gImage_2in13b_r
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ff1f,$ffff,$ffff,$ffff,$ffff,$7ffc
exec $3ffe,$ffff,$ffff,$ffff,$ffff,$f8ff,$fc3f,$ff3f
exec $ffff,$ffff,$ffff,$ffff,$1fc0,$3ff0,$ffff,$ffff
exec $ffff,$ffff,$80ff,$c00f,$ff3f,$ffff,$ffff,$ffff
exec $ffff,$4780,$7f80,$ffff,$ffff,$ffff,$ffff,$80ff
exec $1f02,$ffff,$ffff,$ffff,$ffff,$ffff,$8683,$3f78
exec $ffff,$ffff,$ffff,$ffff,$82ff,$e00c,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$0c80,$0380,$ffff,$ffff,$ffff
exec $ffff,$80ff,$0005,$ff00,$ffff,$ffff,$ffff,$ffff
exec $04c6,$0000,$ffff,$ffff,$ffff,$ffff,$c0ff,$0004
exec $ff01,$ffff,$ffff,$ffff,$ffff,$04e0,$0160,$ffff
exec $ffff,$ffff,$ffff,$f0ff,$6006,$ff01,$ffff,$ffff
exec $ffff,$ffff,$0efc,$0100,$ffff,$ffff,$ffff,$ffff
exec $ffff,$20e2,$ff01,$ffff,$ffff,$ffff,$ffff,$00f0
exec $0310,$ffff,$ffff,$ffff,$ffff,$e0ff,$0080,$ff07
exec $ffff,$ffff,$ffff,$ffff,$80f0,$0718,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$8000,$ff1f,$ffff,$ffff,$ffff
exec $ffff,$c0f0,$3c80,$ff7f,$ffff,$ffff,$ffff,$e0ff
exec $7fc0,$3ff0,$ffff,$ffff,$ffff,$ffff,$60e0,$0040
exec $ff1f,$ffff,$ffff,$ffff,$e0ff,$2038,$0f00,$ffff
exec $ffff,$ffff,$ffff,$1ce0,$0018,$ff1f,$ffff,$ffff
exec $ffff,$fcff,$0c03,$ff0f,$ffff,$ffff,$ffff,$ffff
exec $06ff,$ff03,$ffff,$ffff,$ffff,$ffff,$ffff,$01fc
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$ffc9,$ffff
exec $ffff,$ffff,$ffff,$ffff,$cfc0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$ff47,$ffff,$ffff,$ffff,$ffff
exec $ffff,$07e0,$ffff,$ffff,$ffff,$ffff,$ffff,$e0ff
exec $ff07,$ffff,$ffff,$ffff,$ffff,$ffff,$07f0,$ffff
exec $ffff,$ffff,$ffff,$ffff,$f0ff,$ff3f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$cff9,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffef,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$3fff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f0ff,$ff3f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff0f,$ffff,$ffff,$ffff,$ffff
exec $feff,$0f00,$ffff,$ffff,$ffff,$ffff,$ffff,$00fe
exec $ff07,$ffff,$ffff,$ffff,$ffff,$feff,$0700,$ffff
exec $ffff,$ffff,$ffff,$ffff,$4efe,$ff07,$ffff,$ffff
exec $ffff,$ffff,$feff,$0701,$ffff,$ffff,$ffff,$ffff
exec $ffff,$01fe,$ff07,$ffff,$ffff,$ffff,$ffff,$feff
exec $0f00,$ffff,$ffff,$ffff,$ffff,$ffff,$00fe,$ffff
exec $ffff,$ffff,$ffff,$ffff,$feff,$ff03,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1cfe,$ff01,$ffff,$ffff,$ffff
exec $ffff,$feff,$0068,$ffff,$ffff,$ffff,$ffff,$ffff
exec $c4f0,$7f00,$ffff,$ffff,$ffff,$ffff,$f1ff,$0006
exec $ff3f,$ffff,$ffff,$ffff,$ffff,$03e1,$3f00,$ffff
exec $ffff,$ffff,$ffff,$e2ff,$8001,$ff1f,$ffff,$ffff
exec $ffff,$ffff,$c0c1,$0780,$ffff,$ffff,$ffff,$ffff
exec $c0ff,$c070,$ff0f,$ffff,$ffff,$ffff,$ffff,$38e0
exec $1f00,$ffff,$ffff,$ffff,$ffff,$e0ff,$010c,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1fc0,$8fff,$ffff,$ffff
exec $ffff,$ffff,$80ff,$0070,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$0081,$1f00,$ffff,$ffff,$ffff,$ffff,$c1ff
exec $0000,$ff3f,$ffff,$ffff,$ffff,$ffff,$0fc0,$7fc0
exec $ffff,$ffff,$ffff,$ffff,$e0ff,$c00f,$ffff,$ffff
exec $ffff,$ffff,$ffff,$00f0,$ff3f,$ffff,$ffff,$ffff
exec $ffff,$faff,$0f07,$ffff,$ffff,$ffff,$ffff,$ffff
exec $07fe,$ff07,$ffff,$ffff,$ffff,$ffff,$ffff,$0308
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00ff,$ff03,$ffff
exec $ffff,$ffff,$ffff,$ffff,$01c0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$e0ff,$ff00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$01f8,$ffff,$ffff,$ffff,$ffff,$ffff,$fcff
exec $ff07,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff
