method gImage_2in9bc_ry
return dataaddress(array_gImage_2in9bc_ry)

method gImage_2in9bc_b
return dataaddress(array_gImage_2in9bc_b)

rem 
rem 	This file was copied from Waveshare C library and modified by Katsumi. 
rem 
rem /*****************************************************************************
rem * | File      	:   ImageData.c
rem * | Author      :   Waveshare team
rem * | Function    :	
rem *----------------
rem * |	This version:   V1.1
rem * | Date        :   2019-06-12
rem * | Info        :
rem *
rem #
rem # Permission is hereby granted, free of charge, to any person obtaining a copy
rem # of this software and associated documnetation files (the "Software"), to deal
rem # in the Software without restriction, including without limitation the rights
rem # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
rem # copies of the Software, and to permit persons to  whom the Software is
rem # furished to do so, subject to the following conditions:
rem #
rem # The above copyright notice and this permission notice shall be included in
rem # all copies or substantial portions of the Software.
rem #
rem # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
rem # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
rem # FITNESS OR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
rem # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
rem # LIABILITY WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
rem # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
rem # THE SOFTWARE.
rem #
rem 
rem ******************************************************************************/

label array_gImage_2in9bc_b
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$fffc,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$7ff8,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3ff0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$1fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$1fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$01e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00e0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00e0,$1f78,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00e0,$1f78,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$20e0,$1f38,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$20e0,$0000,$1f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$30e0,$0000,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$38e0,$0000,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$38e0,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3ce0,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3ce0,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$07fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$07fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$03fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$03fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$03fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$03fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$03fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$07fe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$3ffe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$fffe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$3fe0,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffc3,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$7fc0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$1f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0f80,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$0780,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$0740,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$077c,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077e,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$077c,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$0f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$1f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03fe,$e0c0,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$e0c1,$ff7f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$0000,$ff0f,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$c007,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$c007,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07c1,$c0ff,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c021,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c021,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c021,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07c1,$c1ff,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$c100,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07c1,$c1ff,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07c1,$c1ff,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$04c1,$c121,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07c1,$c1ff,$0f06,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$c107,$0ffe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$ff07,$0ffe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c1,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$ff07,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$7fff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c1ff,$ffff,$3fff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c1ff,$ffff,$1ffe,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$ff07,$07fc,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$3f00,$07f8,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0700,$07e0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$0fc0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$1f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$c180,$00fe,$ff00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0180,$00fe,$ff00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0080,$7f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$0000,$1fc0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c0,$0f00,$0fe0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00ff,$7e00,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$7e00,$0304,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$ff00,$0302,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$ff40,$0702,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$1f01,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$bf00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$7f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$8060,$7f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$8060,$3f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$8360,$fff1,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$8360,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$8360,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0080,$8060,$ff03,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0ff,$8060,$7f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$1f00,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$8060,$0700,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f8,$ff60,$07c0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00c8,$ff60,$1ffc,$ffff,$ffff,$ffff
exec $ffff,$ffff,$f0c7,$ff7f,$1fff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$e0c3,$ff3f,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$e080,$0000,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$6080,$0000,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$2080,$0000,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$1880,$0000,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0ee0,$0000,$0300,$ffff,$ffff,$ffff
exec $ffff,$ffff,$07f0,$1f00,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03f8,$0fc0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$01fe,$07e0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$03ff,$07f0,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$0fff,$1ff8,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$9fff,$7ffe,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0000,$0000,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0000,$0040,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0100,$00f0,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0700,$00fc,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$1f00,$00ff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$7f00,$d0ff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff01,$f8ff,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff0f,$fc9f,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$fe1f,$fe03,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$f81f,$ff00,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$f81f,$7f00,$ff81,$ffff,$ffff
exec $ffff,$ffff,$00f0,$fe1f,$ff00,$ffc1,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff0f,$0080,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff03,$00e0,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$7f00,$00fc,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$1f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0700,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$3ff0,$03e0,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$1ff0,$00f0,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$0ff0,$00fe,$003e,$ff01,$ffff,$ffff
exec $ffff,$ffff,$07f0,$80ff,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$03f0,$e0ff,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$01f0,$fcff,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff1f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff07,$00c0,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff00,$00f8,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$3f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$0f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$3f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff07,$00f8,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff1f,$00c0,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$fe1f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$f81f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$f81f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff1f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff03,$00e0,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$7f00,$00fc,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$1f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$3f00,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff01,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff0f,$00fe,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff1f,$00f8,$ff01,$ffff,$ffff
exec $ffff,$ffff,$00f0,$ff1f,$00c0,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$fe1f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$f01f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$801f,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$001c,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$c0ff,$0000,$0000,$ff01,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
label array_gImage_2in9bc_ry
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0c02,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1e03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e301,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c200,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0203,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1b,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1b,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1b,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8001,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff0f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff0f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe0f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0203,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f301,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$b703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0318,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c318,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c318,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c318,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c318,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff1f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f301,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$b703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$9f03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$9f01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0e00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$8003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff3f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0c02,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$1e03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e301,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c200,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f301,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$b703,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$7800,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0002,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f803,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f803,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c003,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0002,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3303,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$9f03,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$9f01,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0e00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0018,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$801f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$f81f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff07,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fe07,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$e01f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$c01f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fc0f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$3f00,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ff07,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$fc1f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$801f,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0018,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$0000,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$00fc,$ff0f,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$ff0f,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$f8ff,$1f00,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
exec $ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff,$ffff
